name: build

on:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18

    steps:
      - name: install
        run: |
          apk add --no-cache make m4 autoconf automake gcc g++ krb5-dev openssl-dev gettext-dev 
          apk add --no-cache libtool libxml2 libxslt libunistring-dev zlib-dev samba-dev
          apk add --no-cache libwbclient

      - name: clone
        run: |
          git clone https://github.com/gssapi/gss-ntlmssp
          cd gss-ntlmssp

      - name: make
        run: |
          autoreconf -f -i
          ./configure --without-manpages --disable-nls
          make install
          ls /usr/local/lib/gssntlmssp -l

      - name: copy output
        run: |
          mkdir ouput
          cp /usr/local/lib/gssntlmssp* ./ouput

      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            ./ouput/*

      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./ouput/*
          asset_name: mything
          tag: "0.${{ env.GITHUB_RUN_NUMBER}}"
          overwrite: true
          body: "auto release"
